### ====================================== Product =====================================
### Create Product
POST {{container.url.http.catalog}}/products
Content-Type: application/json

{
  "name": "Test Product",
  "category": [
    "Books",
    "Fiction"
  ],
  "description": "A sample product created from api.http",
  "imageFile": "book.png",
  "price": 19.99
}

### Get Products List
GET {{container.url.http.catalog}}/products
Content-Type: application/json

### Get One Product By ID
GET {{container.url.http.catalog}}/products/019b2eee-3ded-4fe0-b1b7-64a7346dedd8
Content-Type: application/json


### ====================================== Basket =====================================
### Basket Health Check
GET {{container.url.http.basket}}/health
Content-Type: application/json

### Store Basket
POST {{container.url.http.basket}}/basket
Content-Type: application/json

{
  "cart": {
    "userName": "swn",
    "items": [
      {
        "quantity": 2,
        "color": "Red",
        "price": 500,
        "productId": "019b2eee-3ded-4fe0-b1b7-64a7346dedd8",
        "productName": "IPhone X"
      },
      {
        "quantity": 1,
        "color": "Blue",
        "price": 500,
        "productId": "019b2eee-3ded-4fe0-b1b7-64a7346dedd9",
        "productName": "Samsung 10"
      }
    ]
  }
}

### Get Basket
GET {{container.url.http.basket}}/basket/swn
Content-Type: application/json


### ====================================== Discount =====================================
GRPC {{local.url.http.discount}}/greet.Greeter/SayHello
