### Environment selection:
### Use Rider/IDE selector or set with: @env=Development

### Create Product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Test Product",
  "category": [
    "Books",
    "Fiction"
  ],
  "description": "A sample product created from api.http",
  "imageFile": "book.png",
  "price": 19.99
}

###
GET {{baseUrl}}/products
Content-Type: application/json

###
GET {{baseUrl}}/products/019b2eee-3ded-4fe0-b1b7-64a7346dedd8
Content-Type: application/json