global using BuildingBlocks.Behaviors;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Exceptions.Handler;
global using Carter;
// global using Basket.API.Data;
// global using Basket.API.Exceptions;
global using Basket.API.Models;
global using FluentValidation;
global using Mapster;
global using Marten;
global using Marten.Pagination;
global using MediatR;